### PR TITLE
Unifying shinytest2

### PR DESCRIPTION
**Pull request by kartikeyakirar**
Few improvements to unify the shinytest2
- [x] Title case in description

### CODE REVIEW

**Comment by m7pr** [comment]
@kartikeyakirar should we end up description with a comma if we start with a title case :P?

**Comment by kartikeyakirar** [comment]
Are you referring to the comma after the double quote?
`test_that(desc, code)`

**Comment by m7pr** [comment]
Oh sorry. I meant `.` (dot) : ) dot at the end of the sentence

```
"e2e - tm_a_pca: Module is initialised with the specified defaults in function call"
->
"e2e - tm_a_pca: Module is initialised with the specified defaults in function call."
```

**Comment by kartikeyakirar** [comment]
Got it. `testthat ` doesn’t strictly enforce ending descriptions with a period. it's more about maintaining consistency and  Lets do this. I will update it. 👍

**Review by m7pr — APPROVED** [review]

**Comment by m7pr** [comment]
you have failed tests, try to rerun with an empty commit

**Pull request merged**
