### PR TITLE
[skip vbump] upversion to 0.3.0

### PR DESCRIPTION
**Pull request by donyunardi**
Related with #623

### CODE REVIEW

**Comment by donyunardi** [comment]
We got feedback:

> Thanks, we see:
> 
>    Size of tarball: 9729972 bytes
> 
> Please reduce to less than 5 MB.

I'll see if I can reduce the images for vignettes

**Comment by donyunardi** [comment]
Resize the vignette's png size and got < 5MB.
Rebuild the site locally and the image is still legible to view.

**Comment by donyunardi** [comment]
Resubmit to CRAN.
Awaiting feedback.

**Comment by gogonzo** [comment]
CRAN feedback 
> Please reduce to less than 5 MB.

**Comment by donyunardi** [comment]
I have already resized the package by reducing the vignette's PNG file size and resubmitted it to CRAN.
We're still waiting for CRAN to get back at us.

**Review by pawelru — APPROVED** [review]

**Comment by donyunardi** [comment]
Package is now in CRAN.

**Pull request merged**
