### PR TITLE
using teal.data datasets to cut package size

### PR DESCRIPTION
**Pull request by gogonzo**
This addresses CRAN comments about size of the package. See `R CMD build` to compare sizes. Datasets used in examples are taken from `teal.data`

### CODE REVIEW

**Comment by kartikeyakirar** [comment]
@gogonzo The images in the vignettes directory are larger than the data. Shouldn't we reduce their size?

image

image

**Comment by gogonzo** [comment]
> @gogonzo The images in the vignettes directory are larger than the data. Shouldn't we reduce their size or remove it ?
> 
> image
> image

I guess images are better compressed by `R CMD build` - after removing data package size cut from 4.8MB to <1MB. Can you confirm size of the tar.gz before my commit and after?

I can also remove images if @donyunardi is fine with it.

**Comment by chlebowa** [comment]
> I guess images are better compressed by `R CMD build` - after removing data package size cut from 4.8MB to <1MB. Can you confirm size of the tar.gz before my commit and after?

How?? The images are < 1 MB.

**Comment by gogonzo** [comment]
Closing this as @donyunardi has already resubmitted a package with cut size.

**Comment by chlebowa** [comment]
Removing the datasets from `tmg` and using ones from `teal.data` makes sense anyway. I suggest merging this.

**Comment by gogonzo** [comment]
> Removing the datasets from `tmg` and using ones from `teal.data` makes sense anyway. I suggest merging this.

@donyunardi has already submitted the package. If they reject for some reason I can resurrect this PR

**Pull request closed without merging**
