### PR TITLE
Adds min package version

### PR DESCRIPTION
**Pull request by averissimo**
WIP :: parent issue: https://github.com/insightsengineering/nestdevs-tasks/issues/7

Supersede:
* #527

### 🔴 Checklist for PR Reviewer

- [ ] Tag yourself next to this repo on https://github.com/insightsengineering/nestdevs-tasks/issues/7
- [x] Package versions are the same or higher than `main`
- [x] Package list is the same
  - Only exception is `rmarkdown` (may have been removed on `Suggests`)
- [x] All packages in `Imports`, `Depends` & `Suggests` are in new section `Config/Needs/verdepcheck`
- [x] Added entry to `NEWS.md`
- [x] Last `scheduled.yaml` action was run succesfully _(all 4 strategies)_
  - important: it's not the last commit, it's the one that runs 4 `Scheduled 🕰️ / Dependency` actions
- [x] `scheduled.yaml` SHOULD NOT have any push on any branches

### 🔴 What's needed before merging?

This PR depends on some upstream changes that need to be finalized/merged before being ready to review.

#### Change in code

* `verdepcheck.yml` action (see comments)
  - [x] Remove `on: push` section 
  - [x] Change branch to main

#### PRS

- [x] verdepcheck
  * https://github.com/insightsengineering/verdepcheck/pull/24
  * https://github.com/insightsengineering/verdepcheck/pull/26
- [x] verdepcheck-action
  * https://github.com/insightsengineering/r-verdepcheck-action/pull/16

### Changes description

* Adds minimum version for packages `DESCRIPTION`
* Adds `Config/Need/verdepcheck` section in `DESCRIPTION`
* Updates verdepcheck action

### CODE REVIEW

**Comment by kartikeyakirar** [comment]
> All packages in Imports, Depends & Suggests are in new section Config/Needs/verdepcheck

I cannot find the following packages in the list. I understand from our previous conversation that some packages are included as part of R, so we don't need to mention them. I just want to confirm that all of the following fall into these categories:

```
grid
stats
utils
methods
grid extra
```
Additionally, I've found some additional entries that have not been imported:

```
aphalo/ggpp
baddstats/goftest
```

**Comment by kartikeyakirar** [comment]
> Last scheduled.yaml action was run succesfully (all 4 strategies)
important: it's not the last commit, it's the one that runs 4 Scheduled 🕰️ / Dependency actions

It shows it failed.
image

**Comment by kartikeyakirar** [comment]
@averissimo, I executed verdepcheck::max_deps_check(), but I'm still encountering a pdflatex issue even after installing tinytex. Could you please confirm if I might be overlooking a step here?

```
> verdepcheck::max_deps_check(".")->pp
ℹ Creating library directory: C:\Users\HP\AppData\Local\Temp\RtmpOO1nXD\file463413ee4a19
ℹ Getting 41 pkgs with unknown sizes, 116 (117.02 MB) cached                                          
✔ Cached copy of ggmosaic 0.3.4 (source) is the latest build                  
✔ Cached copy of ggplot2 3.4.3.9000 (source) is the latest build
✔ Cached copy of shiny 1.7.5.9000 (source) is the latest build
✔ Cached copy of shinyTree 0.3.1 (source) is the latest build
✔ Cached copy of teal 0.14.0.9007 (source) is the latest build
✔ Cached copy of checkmate 2.2.0 (source) is the latest build
✔ Cached copy of dplyr 1.1.3.9000 (source) is the latest build
✔ Cached copy of DT 0.29.2 (source) is the latest build    
✔ Cached copy of forcats 1.0.0.9000 (source) is the latest build
✔ Cached copy of logger 0.2.2 (source) is the latest build 
✔ Cached copy of magrittr 2.0.3.9000 (source) is the latest build
✔ Cached copy of scales 1.2.1.9000 (source) is the latest build
✔ Cached copy of tidyr 1.3.0.9000 (source) is the latest build
✔ Cached copy of tidyselect 1.2.0.9000 (source) is the latest build
✔ Cached copy of broom 1.0.5.9000 (source) is the latest build
✔ Cached copy of colourpicker 1.3.0 (source) is the latest build
✔ Cached copy of ggExtra 0.10.1 (source) is the latest build
✔ Cached copy of ggpmisc 0.5.4-1.9000 (source) is the latest build
✔ Cached copy of shinyvalidate 0.1.2 (source) is the latest build
✔ Cached copy of shinyWidgets 0.8.0 (source) is the latest build
✔ Cached copy of stringr 1.5.0.9000 (source) is the latest build
✔ Cached copy of teal.code 0.4.1.9000 (source) is the latest build
✔ Cached copy of teal.logger 0.1.3.9005 (source) is the latest build
✔ Cached copy of teal.reporter 0.2.1.9002 (source) is the latest build
✔ Cached copy of teal.transform 0.4.0.9003 (source) is the latest build
✔ Cached copy of teal.widgets 0.4.0.9008 (source) is the latest build
✔ Cached copy of tibble 3.2.1.9005 (source) is the latest build
✔ Cached copy of teal.slice 0.4.0.9012 (source) is the latest build
✔ Cached copy of tern 0.9.0.9005 (source) is the latest build
✔ Cached copy of ggpp 0.5.4 (source) is the latest build   
✔ Cached copy of nestcolor 0.1.2.9004 (source) is the latest build
✔ Cached copy of rlang 1.1.1.9000 (source) is the latest build
✔ Cached copy of rtables 0.6.3.9000 (source) is the latest build
✔ Cached copy of goftest 1.2-2 (source) is the latest build
✔ Cached copy of htmlwidgets 1.6.2.9000 (source) is the latest build
✔ Cached copy of jsonlite 1.8.7 (source) is the latest build
✔ Cached copy of teal.data 0.3.0.9004 (source) is the latest build
✔ Cached copy of testthat 3.1.10.9000 (source) is the latest build
✔ Cached copy of shinyjs 2.1.0.9005 (source) is the latest build
✔ Cached copy of knitr 1.44.1 (source) is the latest build 
✔ Cached copy of lattice 0.21-9 (source) is the latest build
✔ No downloads needed, all packages are cached                                 
✔ Installed MatrixModels 0.5-2  (666ms)                                                    
✔ Installed Matrix 1.6-1  (768ms)                    
✔ Installed R.cache 0.16.0  (851ms)                  
✔ Installed R.methodsS3 1.8.2  (994ms)                
✔ Installed R.oo 1.25.0  (1.1s)                       
✔ Installed R.utils 2.12.2  (1.4s)                                                              
✔ Installed R6 2.5.1  (1.5s)                                                                  
✔ Installed RColorBrewer 1.1-3  (1.8s)                                                  
✔ Installed Rdpack 2.5  (377ms)                                                       
✔ Installed Rcpp 1.0.11  (1.5s)                                                        
✔ Installed SparseM 1.81  (1.3s)                                                        
✔ Installed abind 1.4-5  (253ms)                                                        
✔ Installed TH.data 1.1-2  (1.2s)                                                         
✔ Installed anytime 0.3.9  (545ms)                                                          
✔ Installed backports 1.4.1  (288ms)                                                        
✔ Installed base64enc 0.1-3  (105ms)                                                      
✔ Installed askpass 1.2.0  (1.2s)                                                
✔ Installed brio 1.1.3  (257ms)                                               
✔ Installed cachem 1.0.8  (204ms)                                             
✔ Installed bslib 0.5.1  (1.1s)                                              
✔ Installed callr 3.7.3  (817ms)                                               
✔ Installed carData 3.0-5  (624ms)                                                
✔ Installed car 3.1-2  (545ms)                                                       
✔ Installed commonmark 1.9.0  (111ms)                                                       
✔ Installed cli 3.6.1  (1.2s)                                                             
✔ Installed confintr 1.0.2  (380ms)                                                       
✔ Installed colorspace 2.1-0  (1.5s)                                                       
✔ Installed cowplot 1.1.1  (600ms)                                                                
✔ Installed cpp11 0.4.6  (772ms)                                                                
✔ Installed crayon 1.5.2  (994ms)                                                                 
✔ Installed crosstalk 1.2.0  (1.4s)                                                             
✔ Installed curl 5.0.2  (1.5s)                        
✔ Installed data.table 1.14.8  (1.5s)                 
✔ Installed estimability 1.4.1  (466ms)               
✔ Installed desc 1.4.2  (2s)                          
✔ Installed evaluate 0.21  (267ms)                    
✔ Installed diffobj 0.3.5  (2.1s)                                                                
✔ Installed digest 0.6.33  (2.3s)                     
✔ Installed ellipsis 0.3.2  (2.5s)                    
✔ Installed formatters 0.5.2  (525ms)                 
✔ Installed emmeans 1.8.8  (3s)                       
✔ Installed fansi 1.0.4  (1.7s)                       
✔ Installed farver 2.1.1  (2s)                        
✔ Installed fastmap 1.1.1  (2.3s)                     
✔ Installed fontawesome 0.5.2  (2.5s)                 
✔ Installed highr 0.10  (288ms)                       
✔ Installed fs 1.6.3  (2s)                            
✔ Installed generics 0.1.3  (2.1s)                    
✔ Installed httr 1.4.7  (407ms)                       
✔ Installed ggrepel 0.9.3  (2.3s)                     
✔ Installed glue 1.6.2  (2.6s)                        
✔ Installed gridExtra 2.3  (2.5s)                     
✔ Installed gtable 0.3.4  (2.8s)                      
✔ Installed lazyeval 0.2.2  (303ms)                   
✔ Installed htmltools 0.5.6  (2.7s)                   
✔ Installed httpuv 1.6.11  (2.9s)                     
✔ Installed lmodel2 1.7-3  (328ms)                    
✔ Installed isoband 0.2.7  (2.6s)                     
✔ Installed jquerylib 0.1.4  (2.6s)                   
✔ Installed memoise 2.0.1  (268ms)                    
✔ Installed mime 0.12  (94ms)                         
✔ Installed labeling 0.4.3  (3.2s)                    
✔ Installed miniUI 0.1.1.1  (259ms)                   
✔ Installed later 1.3.1  (3.5s)                                                                 
✔ Installed minqa 1.2.5  (268ms)                      
✔ Installed multcompView 0.1-9  (90ms)                                                          
✔ Installed lifecycle 1.0.3  (3.3s)                                                                  
✔ Installed lme4 1.1-34  (3.5s)                                                                    
✔ Installed lubridate 1.9.2  (3.1s)                                                                 
✔ Installed multcomp 1.4-25  (1.3s)                   
✔ Installed munsell 0.5.0  (1.3s)                     
✔ Installed pkgconfig 2.0.3  (111ms)                  
✔ Installed mvtnorm 1.2-3  (1.8s)                     
✔ Installed pkgload 1.3.2.1  (258ms)                  
✔ Installed nloptr 2.0.3  (1.9s)                      
✔ Installed numDeriv 2016.8-1.1  (2.4s)               
✔ Installed openssl 2.1.0  (2.6s)                     
✔ Installed productplots 0.1.1  (97ms)                
✔ Installed pbkrtest 0.5.2  (3s)                      
✔ Installed pillar 1.9.0  (3.1s)                      
✔ Installed plotly 4.10.2  (2.4s)                     
✔ Installed plyr 1.8.8  (2.3s)                        
✔ Installed rappdirs 0.3.3  (114ms)                   
✔ Installed polynom 1.4-1  (2.7s)                     
✔ Installed rematch2 2.1.2  (126ms)                   
✔ Installed praise 1.0.0  (2.9s)                      
✔ Installed processx 3.8.2  (3.3s)                    
✔ Installed promises 1.2.1  (3s)                      
✔ Installed ps 1.7.5  (3s)                            
✔ Installed purrr 1.0.2  (3s)                         
✔ Installed quantreg 5.97  (3s)                       
✔ Installed rbibutils 2.2.15  (2.8s)                  
✔ Installed rmarkdown 2.24  (2.5s)                     
✔ Installed rprojroot 2.0.3  (2.3s)                    
✔ Installed sys 3.4.2  (213ms)                         
✔ Installed sandwich 3.0-2  (2.7s)                     
✔ Installed timechange 0.2.0  (285ms)                  
✔ Installed sass 0.4.7  (2.8s)                         
✔ Installed tinytex 0.46  (265ms)                      
✔ Installed sourcetools 0.1.7-1  (3s)                  
✔ Installed sparkline 2.0  (3.1s)                      
✔ Installed waldo 0.5.1  (111ms)                       
✔ Installed splus2R 1.3-3  (3.2s)                      
✔ Installed stringi 1.7.12  (3.2s)                     
✔ Installed xtable 1.8-4  (142ms)                      
✔ Installed styler 1.10.2  (3.8s)                      
✔ Installed yaml 2.3.7  (108ms)                        
✔ Installed utf8 1.2.3  (2.6s)                         
✔ Installed vctrs 0.6.3  (2.5s)                        
✔ Installed viridisLite 0.4.2  (2.9s)                  
✔ Installed ggmosaic 0.3.4 (github::haleyjeppson/ggmosaic@b8045be) (324ms)
✔ Installed withr 2.5.0  (3s)                                                                       
✔ Installed xfun 0.40  (3.3s)                                                                      
✔ Installed xts 0.13.1  (3.1s)                         
✔ Installed zip 2.3.0  (2.8s)                          
✔ Installed zoo 1.8-12  (3s)                           
✔ Installed ggplot2 3.4.3.9000 (github::tidyverse/ggplot2@954924b) (2.5s)
✔ Installed shiny 1.7.5.9000 (github::rstudio/shiny@eddc304) (2.8s)
✔ Installed teal 0.14.0.9007 (github::insightsengineering/teal@139971a) (2.7s)
✔ Installed magrittr 2.0.3.9000 (github::tidyverse/magrittr@21093d0) (303ms)
✔ Installed shinyTree 0.3.1 (github::shinyTree/shinyTree@110b499) (3.2s)
✔ Installed checkmate 2.2.0 (github::mllg/checkmate@c21c718) (2.9s)
✔ Installed dplyr 1.1.3.9000 (github::tidyverse/dplyr@7374271) (2.6s)
✔ Installed DT 0.29.2 (github::rstudio/DT@b6de4ac) (2.5s)                                           
✔ Installed forcats 1.0.0.9000 (github::tidyverse/forcats@4a8525a) (2.3s)                         
✔ Installed logger 0.2.2 (github::daroczig/logger@829aabb) (2s)                            
✔ Installed scales 1.2.1.9000 (github::r-lib/scales@b3df2fb) (1.4s)                    
✔ Installed tidyselect 1.2.0.9000 (github::r-lib/tidyselect@7cc3ea6) (95ms)        
✔ Installed tidyr 1.3.0.9000 (github::tidyverse/tidyr@0764e65) (599ms)           
✔ Installed broom 1.0.5.9000 (github::tidymodels/broom@db2ca13) (626ms)                       
✔ Installed colourpicker 1.3.0 (github::daattali/colourpicker@8bd9604) (665ms)                
✔ Installed ggExtra 0.10.1 (github::daattali/ggExtra@5321e4a) (944ms)                          
✔ Installed ggpmisc 0.5.4-1.9000 (github::aphalo/ggpmisc@e1120ae) (1.1s)
✔ Installed shinyvalidate 0.1.2 (github::rstudio/shinyvalidate@575f586) (1.5s)
✔ Installed stringr 1.5.0.9000 (github::tidyverse/stringr@08ff36f) (1.5s)
✔ Installed shinyWidgets 0.8.0 (github::dreamRs/shinyWidgets@daad7e8) (2s)
✔ Installed teal.code 0.4.1.9000 (github::insightsengineering/teal.code@41f660b) (1.7s)
✔ Installed teal.logger 0.1.3.9005 (github::insightsengineering/teal.logger@16ef533) (1.6s)
✔ Installed teal.reporter 0.2.1.9002 (github::insightsengineering/teal.reporter@89546d6) (1.5s)
✔ Installed teal.transform 0.4.0.9003 (github::insightsengineering/teal.transform@b1edf92) (1.7s)
✔ Installed teal.widgets 0.4.0.9008 (github::insightsengineering/teal.widgets@9e84d07) (1.7s)
✔ Installed goftest 1.2-2 (github::baddstats/goftest@ef942bf) (164ms)
✔ Installed tibble 3.2.1.9005 (github::tidyverse/tibble@4de5c15) (2.2s)
✔ Installed htmlwidgets 1.6.2.9000 (github::ramnathv/htmlwidgets@d31dd27) (288ms)
✔ Installed jsonlite 1.8.7 (github::jeroen/jsonlite@2d527d9) (101ms)
✔ Installed teal.slice 0.4.0.9012 (github::insightsengineering/teal.slice@d968458) (2.6s)
✔ Installed tern 0.9.0.9005 (github::insightsengineering/tern@5f34f7c) (3s)
✔ Installed ggpp 0.5.4 (github::aphalo/ggpp@e6f60a2) (3s)
✔ Installed nestcolor 0.1.2.9004 (github::insightsengineering/nestcolor@103298c) (3.1s)
✔ Installed rlang 1.1.1.9000 (github::r-lib/rlang@c55f602) (3.2s)
✔ Installed rtables 0.6.3.9000 (github::insightsengineering/rtables@8f01282) (3.2s)
✔ Installed teal.data 0.3.0.9004 (github::insightsengineering/teal.data@5898a1a) (2.2s)
✔ Installed testthat 3.1.10.9000 (github::r-lib/testthat@29018e0) (2.2s)
✔ Installed shinyjs 2.1.0.9005 (github::daattali/shinyjs@67b269d) (2.3s)
✔ Installed knitr 1.44.1 (github::yihui/knitr@768db6f) (2.2s)                                    
✔ Installed lattice 0.21-9 (github::deepayan/lattice@e2f44f5) (2s)                             
✔ Installed shinycssloaders 1.0.0  (2.1s)                                               
── R CMD build ───────────────────────────────────────────────────────────────────────────────────────
pdflatex not found! Not building PDF manual.
✔  checking for file 'C:\Users\HP\Documents\roche\teal.modules.general/DESCRIPTION'
─  preparing 'teal.modules.general':
✔  checking DESCRIPTION meta-information ... 
─  installing the package to build vignettes
✔  creating vignettes (24.9s)
─  checking for LF line-endings in source and make files and shell scripts (349ms)
─  checking for empty or unneeded directories
─  building 'teal.modules.general_0.2.16.9006.tar.gz'
   
── R CMD check ───────────────────────────────────────────────────────────────────────────────────────
─  using log directory 'C:/Users/HP/AppData/Local/Temp/RtmpOO1nXD/file463422df7616/teal.modules.general.Rcheck'
─  using R version 4.3.1 (2023-06-16 ucrt)
─  using platform: x86_64-w64-mingw32 (64-bit)
─  R was compiled by
       gcc.exe (GCC) 12.2.0
       GNU Fortran (GCC) 12.2.0
─  running under: Windows 11 x64 (build 22621)
─  using session charset: UTF-8
✔  checking for file 'teal.modules.general/DESCRIPTION' ...
─  checking extension type ... Package
─  this is package 'teal.modules.general' version '0.2.16.9006'
─  package encoding: UTF-8
✔  checking package namespace information
✔  checking package dependencies (1.3s)
✔  checking if this is a source package ...
✔  checking if there is a namespace
✔  checking for executable files (1.5s)
✔  checking for hidden files and directories ...
✔  checking for portable file names
✔  checking whether package 'teal.modules.general' can be installed (10s)
✔  checking installed package size ... 
✔  checking package directory
✔  checking 'build' directory
✔  checking DESCRIPTION meta-information ... 
✔  checking top-level files
✔  checking for left-over files ...
✔  checking index information ... 
✔  checking package subdirectories ... 
✔  checking R files for non-ASCII characters ... 
✔  checking R files for syntax errors ... 
✔  checking whether the package can be loaded (1.3s)
✔  checking whether the package can be loaded with stated dependencies (1.3s)
✔  checking whether the package can be unloaded cleanly (1.3s)
✔  checking whether the namespace can be loaded with stated dependencies (1s)
✔  checking whether the namespace can be unloaded cleanly (1.2s)
✔  checking loading without being on the library search path (1.8s)
✔  checking startup messages can be suppressed (2.6s)
✔  checking dependencies in R code (3s)
✔  checking S3 generic/method consistency (1.3s)
✔  checking replacement functions (1.1s)
✔  checking foreign function calls (1.4s)
✔  checking R code for possible problems (7.7s)
✔  checking Rd files (565ms)
✔  checking Rd metadata ... 
✔  checking Rd cross-references ... 
✔  checking for missing documentation entries (1.4s)
✔  checking for code/documentation mismatches (4.1s)
✔  checking Rd \usage sections (1.5s)
✔  checking Rd contents ... 
✔  checking for unstated dependencies in examples (458ms)
✔  checking contents of 'data' directory (447ms)
✔  checking data for non-ASCII characters (562ms)
✔  checking LazyData
✔  checking data for ASCII and uncompressed saves ... 
✔  checking installed files from 'inst/doc' ... 
✔  checking files in 'vignettes' ... 
✔  checking examples (6.6s)
✔  checking for unstated dependencies in 'tests' ... 
─  checking tests ...
✔  Running 'testthat.R' (1.8s)
✔  checking for unstated dependencies in vignettes (377ms)
✔  checking package vignettes in 'inst/doc' ... 
─  checking running R code from vignettes
     'teal-modules-general.Rmd' using 'UTF-8'... OK
     'using-association-plot.Rmd' using 'UTF-8'... OK
     'using-bivariate-plot.Rmd' using 'UTF-8'... OK
     'using-cross-table.Rmd' using 'UTF-8'... OK
     'using-data-table.Rmd' using 'UTF-8'... OK
     'using-outliers-module.Rmd' using 'UTF-8'... OK
     'using-regression-plots.Rmd' using 'UTF-8'... OK
     'using-response-plot.Rmd' using 'UTF-8'... OK
     'using-scatterplot-matrix.Rmd' using 'UTF-8'... OK
     'using-scatterplot.Rmd' using 'UTF-8'... OK
    NONE
✔  checking re-building of vignette outputs (30.3s)
W  checking PDF version of manual (927ms)
   LaTeX errors when creating PDF version.
   This typically indicates Rd problems.
E  checking PDF version of manual without index (699ms)
   Re-running with no redirection of stdout/stderr.
   Hmm ... looks like a package
   Converting parsed Rd's to LaTeX ....
   Creating pdf output from LaTeX ...
   Error in texi2dvi(file = file, pdf = TRUE, clean = clean, quiet = quiet,  : 
     pdflatex is not available
   Error in texi2dvi(file = file, pdf = TRUE, clean = clean, quiet = quiet,  : 
     pdflatex is not available
   Error in running tools::texi2pdf()
   You may want to clean up by 'rm -Rf C:/Users/HP/AppData/Local/Temp/RtmpArXYXK/Rd2pdf5fbc7c076103'
   
   See
     'C:/Users/HP/AppData/Local/Temp/RtmpOO1nXD/file463422df7616/teal.modules.general.Rcheck/00check.log'
   for details.
   
```

**Comment by averissimo** [comment]
@kartikeyakirar can you run `pdflatex -v` on the console or `system("pdflatex -v")` in R's console

`pdflatex` is a system dependency for the `R CMD check` :-\

ps. I've rebased the branch

**Review by kartikeyakirar — APPROVED** [review]
checks run successfully https://github.com/insightsengineering/teal.modules.general/actions/runs/6182179703
LGTM 👍 

> Additionally, I've found some additional entries that have not been imported:

Could you comment on this? before merging this

**Comment by averissimo** [comment]
@kartikeyakirar Nice one for noticing it!

I was already going to change the PR, but then saw that those two dependencies are in `Suggests`, they're just hidden from the "Files changed" (GitHub interface failed us here :sweat_smile:)

https://github.com/insightsengineering/teal.modules.general/blob/1fb3f986b512b2e13e6e6db18a6af42c69ed5e56/DESCRIPTION#L53-L58

image

**Comment by kartikeyakirar** [comment]
@averissimo  thanks for explanation. My mistake; I overlooked that part while comparing.

**Pull request merged**
