### PR TITLE
Fixing inconsistent Styling and Layout for 'Show Warning' and 'Show R Code' Buttons

### PR DESCRIPTION
**Pull request by kartikeyakirar**
this fixes https://github.com/insightsengineering/teal.modules.general/issues/568

### CODE REVIEW

**Comment by chlebowa** [comment]
The implementation is markedly different to that in other modules. Why are the buttons in a conditional panel?

**Comment by pawelru** [comment]
idea: maybe worth to move datasets picker to the column selection area so that we will get rid off one rows for datasets?

**Comment by kartikeyakirar** [comment]
> idea: maybe worth to move datasets picker to the column selection area so that we will get rid off one rows for datasets?

I think this is Good idea. And feasibly, we could remove the 'datasets' subsection under the 'Encoding' label and replace it with a dropdown. However, I'm uncertain about other aspects of the design in relation to this change. Since this falls outside the scope of the current task, I'll create a separate task to initiate a discussion on this matter.

**Comment by kartikeyakirar** [comment]
replaced `tern::summarize_vars` with `tern::analyze_vars` as summarize_vars is deprecated.

**Review by chlebowa — APPROVED** [review]

**Pull request merged**
