### PR TITLE
Remove the internal function `var_labels` in favour of `teal.data::col_labels`

### LINKED ISSUE #689: Replace `var_labels` with `teal.data::col_labels`
Since both these functions do the same thing. The internal function `var_labels` could be removed in favour of `teal.data::col_labels`.

### PR DESCRIPTION
**Pull request by vedhav**
Closes #689

### CODE REVIEW

**Review by gogonzo — APPROVED** [review]
I appreciate every commit with negative line balance

**Comment by m7pr** [comment]
> I appreciate every commit with negative line balance

Should this be our motto ;) ?

**Comment by chlebowa** [comment]
What happened to this? https://github.com/insightsengineering/teal.modules.general/pull/673

**Comment by gogonzo** [comment]
> What happened to this? https://github.com/insightsengineering/teal.modules.general/pull/673

We are going to have a conflict on main. @chlebowa Your PR went to `prerelease` why this to `main`

**Comment by m7pr** [comment]
@vedhav you did it to main. This change was already on `pre-release@main` lol

**Comment by vedhav** [comment]
🤦🏽 Sorry, I did not know about this. I should have checked the pre-release branch before I did this.

**Comment by chlebowa** [comment]
Pay attention, please.

**Pull request merged**
