### PR TITLE
added checks to resolve issue with the outlier function

### LINKED ISSUE #768: [Bug]: `tm_outliers` can not create a report card / `Error : Can't subset columns that don't exist. ✖ Column order doesn't exist.`
For [exploratory app](https://github.com/insightsengineering/teal.gallery/tree/main/exploratory)

1. Go to Outliers module, 
2. Select categorical factor: PARAM
3. Try adding a report card.

On `Add Card` you will see

> The card could not be added to the report. Have the outputs for the report been created yet? If not please try again when they are ready. Otherwise contact your application developer

image

Checked on `669_insertUI@main` branches for: `teal.slice`. `teal` and `teal.data`

### PR DESCRIPTION
**Pull request by PritDash**
# Pull Request

Fixes #768 

The reproducible example is in the linked issue.

Issue:

The outlier package threw the following error when trying to add a card:

```
Warning in observe() :
  The card could not be added to the report. Have the outputs for the report been created yet? If not please try again when they are ready. Otherwise contact your application developer
Error : Can't subset columns that don't exist.
✖ Column `order` doesn't exist. 
 when evaluating qenv code:
ANL_OUTLIER_EXTENDED[ANL_OUTLIER_EXTENDED$is_outlier_selected, columns_index]
```

Solution:

removed order column as it cannot be in the ANL_OUTLIER_EXTENDED dataframe

```
setdiff(names(ANL_OUTLIER), c("is_outlier_selected", "order"))
```

### CODE REVIEW

**Comment by PritDash** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by PritDash** [comment]
Please undraft this PR and it is ready for review. @m7pr @gogonzo

**Comment by Polkas** [comment]
We found the same issue and it is a blocker for us. Thus so we proposed an update:)

**Comment by m7pr** [comment]
Hey, sorry, I was off last week and didn't see the notification. I will review in the morning

**Review by donyunardi — APPROVED** [review]
LGTM. Thanks you @PritDash !

**Pull request merged**
